### ISSUE TITLE
Wikipedia license link correct but appears as undefined

### ISSUE THREAD

**Issue by pgogy** [nyergler/openattribute-firefox#14]
http://en.wikipedia.org/wiki/William_Laud

This HTML

<a rel="license" href="http://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License">Creative Commons Attribution-ShareAlike License</a><a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/" style="display:none;"></a>

Seems to confuse version 0.8 and 0.81

**Comment by nyergler** [comment]
I'm on the fence about how much to really hack around this. If WikiMedia wants to publish their own license pages, that's fine. I suspect we should update the license retriever (module/license.js) so that if it can't get the title of the license from RDFa, it uses the document title instead. That'd be a start.

**Comment by pgogy** [comment]
My hack almost works - your call  (I am off to bed soon)

**Comment by pgogy** [comment]
Oh, this one is fixed in my code - its wikimedia i need to fix.

**Comment by nyergler** [comment]
Just re-read your comment about the update to RDFa.js. I'll look at that more closely tomorrow and see about applying. I wonder if we're going to have these "hacks", it might be good to have them segregated from the normal RDFa processing. Maybe something that gets called from parse, after the initial RDFa parsing? 

Haven't thought about it carefully, I'll look at the changesets in your fork.

**Comment by pgogy** [comment]
Well haven't done wikimedia yet - but the wikipedia one on my version 0.81 brings up an undefined where the license name should be (the link works).

Agree a handler outside the RDFA.js would work better. Perhaps a per URL / site solution could work - so people could add their own? Or would their be too many?

**Comment by pgogy** [comment]
Send a pull request

**Comment by nyergler** [comment]
Added site hack for wikipedias (and secure access) in ff1d07972174b908eaea9f073a56e54b95cea422
