### ISSUE TITLE
RDF code in Chrome missing closing div

### ISSUE THREAD

**Issue by efc** [nyergler/openattribute-firefox#21]
I just tried the plugin for Chrome with a Flickr image. One problem found with the RDF code it generates. The code finished up with a 
    </a></a>
when I think what you wanted was a 
    </a></div>
Right now the
    <div>
opened at the top never closes.

P.S. I tried reporting this in the openattribute-chrome project, but I could not find an "issues" section on that project. Sorry!

**Comment by pgogy** [comment]
https://github.com/patlockley/openattribute-chrome/issues
