### ISSUE TITLE
Chrome plugin confused by multiple tabs

### ISSUE THREAD

**Issue by efc** [nyergler/openattribute-firefox#22]
Scenario: I have this github issues page in a tab on Chrome, and Flickr in another tab with a CC licensed image open. When I first open the Flickr page, all is well and the plugin shows info for the Flickr page. But if I then click on the github issues tab and reload that page, then return to the Flickr tab without reloading, the plugin will show info for the _last loaded_ page rather than the page in the _current tab_. Since the pugin's icon is in the location text area with the URL of the current tab's page, this is very confusing behavior!

P.S. I tried reporting this in the openattribute-chrome project, but I could not find an "issues" section on that project. Sorry!

**Comment by nyergler** [comment]
This has been reported and fixed in Chrome -- https://github.com/patlockley/openattribute-chrome/issues/closed#issue/9
