### ISSUE TITLE
Attribution includes wrong URL on Flickr pages?

### ISSUE THREAD

**Issue by jbj-ph** [nyergler/openattribute-firefox#24]
When using the Firefox version, the plain text atttribution includes the wrong link.  (Not a link to the picture itself or to the photo page, but to a page that's not useful.)

You can see what I'm talking about here: http://www.flickr.com/photos/jbj/5430272556/sizes/o/

**Comment by nyergler** [comment]
This has been corrected in commit 5a7c075d5a70e725f4083db6ff38ea3349b538e2 and is included in 0.9.3, which can be downloaded from https://addons.mozilla.org/en-US/firefox/addon/openattribute/versions/0.9.3 (currently awaiting review).
