### ISSUE TITLE
Does not work on Ipernity

### ISSUE THREAD

**Issue by forteller** [nyergler/openattribute-firefox#26]
I just wanted to let you know that OA does not detect CC licensed pictures shared on the Flickr like site Ipernity.

Here are some examples (all of these are CC licensed): http://www.ipernity.com/doc/forteller/album/51187

I hope that's something that can be easily fixed. :)

**Comment by nyergler** [comment]
Ipernity is not publishing any license or attribution metadata, which OpenAttribute (and other tools) rely on. If you have a contact there, I'm happy to work with them to update their site.

**Comment by forteller** [comment]
I see. I'm just a regular user, so I can't do much. But at least I have now sent them a bug report about this and told them that you'd like to help.

I'm sure it'd be a good idea if you contact them directly too, though. http://www.ipernity.com/help/support
