### ISSUE TITLE
Not compatible with FF 5

### ISSUE THREAD

**Issue by aqeeliz** [nyergler/openattribute-firefox#32]
Firefox 5 is officially released, and apparently the plugin is not compatible with it. 

In case it it just an issue with the version settings of the plugin, what about increasing the max version of FF (compatible with the plugin) to some great number, as Firefox is going to release 4 major releases every year, it would save from plugin not working with new versions, when it breaks, it can be fixed for that version.

**Comment by nyergler** [comment]
addons.mozilla.org doesn't allow publishing add-ons with "invalid" (ie, not released) version numbers. We'll just need to push a new update that explicitly supports Fx 5.

**Comment by nyergler** [comment]
Fixed in commit f6ff07a19f1c89be3efa, to be included in new 0.9.7 release.

**Comment by nyergler** [comment]
New release currently under review at Mozilla; you can download pre-review from https://addons.mozilla.org/en-US/firefox/addon/openattribute/versions/0.9.7. Thanks for reporting the issue!
