### ISSUE TITLE
"undefined" license when used with HTTPS Everywhere enabled

### ISSUE THREAD

**Issue by mlinksva** [nyergler/openattribute-firefox#36]
Using OA0.8.1 with Firefox 8.0a2 Linux (enabled with compatibility checker) I get licenses detected, but after momentary correct display, the license is "undefined". ex page info screenshot http://gondwanaland.com/tmp/openattribute-undefinedlicense.png

This occurs when license url redirects, as happens with HTTPS Everywhere enabled at the creativecommons.org site [actually I'm not sure this demonstrates that server instigated redirects won't be followed, as I'm not sure how HTTPS Everywhere works, so making this bug HTTPS Everywhere specific].

**Comment by nyergler** [comment]
Haven't looked at this yet, but is it happening for all pages, or just particular ones?

**Comment by mlinksva** [comment]
All pages on which a CC license is detected. :)

**Comment by nyergler** [comment]
Are you using the HTTPS Everywhere add-on?

**Comment by mlinksva** [comment]
Yes. I turned HTTPS Everywhere off and this bug goes away. Should've thought of that.

I don't see an issue concerning handling redirection (maybe 16, which I'm not sure what it is saying), so I'll add to the description of this one.

**Comment by nyergler** [comment]
I believe I have a fix for this in commit 5fdc2e83. This will go out in the next release.

Issue 16 is different (and probably a "wont-fix"): the example given there has a bogus URL for the license, which then redirects to the actual license.

**Comment by nyergler** [comment]
You can download a new release for testing from https://addons.mozilla.org/en-US/firefox/addon/openattribute/versions/0.9.8. Please re-open this issue if you still encounter problems.

**Comment by mlinksva** [comment]
Works with HTTPS Everywhere enabled, thanks!
