### ISSUE TITLE
Attribution HTML on Flickr does not include the creator

### ISSUE THREAD

**Issue by nyergler** [nyergler/openattribute-firefox#4]
Flickr annotates the license with RDFa, but removed RDFa markup for the creator when their new look was deployed.

**Comment by pgogy** [comment]
Have sent my code up for this - so will send a pull request.

**Comment by nyergler** [comment]
Committed modified version in ceb2f31c5affeedc4e962bb589eea531d0519a88.

6f6bdc651de94ced958d9b0d70cddf44332b42dd sets up the framework for implementing additional site-specific hacks, if needed :/.

**Comment by pgogy** [comment]
Cool :)
