### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by forteller** [nyergler/openattribute-firefox#41]
I really like this plugin, but it seems like it's not being maintained. That makes me very wary of installing it, because of fear of security holes. Are there any plans to update it?

Thanks!

**Comment by nyergler** [comment]
I'm not devoting development time to the extension, but am available to review PRs and bug reports (such as this one!). I'm not sure what sort of update would assuage your fear of security holes, but I'm unlikely to provide it on my own.

**Comment by nogweii** [comment]
While it may not be actively developed, the related structure also hasn't changed. It still works quite well!
